---
- name: insatllation du serveur web
  become: yes
  hosts: web
  tasks: 
  
  - name: installer httpd
    yum:
      update_cache: yes
      name: httpd
      state: present

  - name: lancer le service httpd
    service:
      name: httpd
      state: started
      enabled: yes
  
