---
- name: installer MySQL, faire les configurations et creer les bases de donnees et les utilisateurs necessaires
  hosts: localhost
  become: yes
  vars_files: ../vars/main.yml
  tasks:
  
  - name: télecharger le repository pour MySQL
    get_url: 
      url: https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
      dest: /tmp/mysql80-community-release-el7-3.noarch.rpm
  
  - name: ajouter le repository mysql 
    shell: 
      cmd: " sudo rpm -Uvh /tmp/mysql80-community-release-el7-3.noarch.rpm"
    ignore_errors: yes

  - name: installer MySQL
    yum: 
      name:
        - mysql-community-server
      update_cache: yes

  - name: start mysqld
    systemd:
      name: mysqld
      state: started
      enabled: yes

  - name: installer MySQL-python pour gerer des utilisateurs et bases de données
    yum:
      name:
      - gcc-c++
      - MySQL-python 
      update_cache: yes
  
  - name: trouver le mot de passe temporaire du root
    shell: 
      cmd: 'cat /var/log/mysqld.log | grep root@localhost:| cut -d : -f 4| cut -d " " -f 2'
    register: mysql_root_temp_password

  - name: changer le mot de passe du root 
    shell: mysqladmin -u root --password="{{ mysql_root_temp_password.stdout }}" password "{{ root_password }}"
    register: mysql_admin_root_password_result
    failed_when: "'(using password: NO)' in mysql_admin_root_password_result.stderr"

  - name: copier le fichier template table.sql.j2 dans le répertoire /tmp/
    template:
      src: ../templates/table.sql.j2
      dest: /tmp/table.sql 
